package com.mez.api.models;

import com.mez.api.tools.annotations.AutoGenerated;
import com.mez.api.tools.annotations.PrimaryKey;
import lombok.Data;

@Data
public class Post {

  @PrimaryKey
  @AutoGenerated
  private int id;
  private String title;
  private String date;
  private String beforePhotoText;
  private String photo;
  private String afterPhotoText;
  private int views = 0;
  private String tags;
}
